default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: activerecorder_development

test:
  <<: *default
  database: activerecorder_test

production:
  <<: *default
  database: activerecorder_production
  username: activerecorder
  password: <%= ENV['ACTIVERECORDER_DATABASE_PASSWORD'] %>
