default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: activerecorder_back_development

test:
  <<: *default
  database: activerecorder_back_test

production:
  <<: *default
  database: activerecorder_back_production
  password: <%= ENV["DATABASE_URL"] %>
